version: '3.3'
services:

  keycloak:
    container_name: keycloak
    image: 'ghcr.io/udi-service/udiaas-keycloak:latest'
    command: start --optimized
    restart: always
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB_DATABASE=$POSTGRES_KEYCLOAK_DB
      - KC_DB_URL=jdbc:postgresql://postgres/${KC_DB_DATABASE}
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_FQDN}
    networks:
      - network
    ports:
      - '${KEYCLOAK_PORT:-8080}:8080'

  postgres:
    container_name: udiaas-postgres
    image: 'ghcr.io/udi-service/udiaas:15.4'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - network
    ports:
      - '5432:5432'

  postgREST:
    container_name: udiaas-postgrest
    image: postgrest/postgrest:v11.2.1
    restart: always
    environment:
      PGRST_DB_URI: ${POSTGREST_DB_URI}
      PGRST_DB_SCHEMA: ${POSTGREST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${POSTGREST_DB_ANON_ROLE}
      PGRST_SERVER_PORT: ${POSTGREST_SERVER_PORT}
      PGRST_JWT_SECRET: ${POSTGREST_JWT_SECRET}
    ports:
      - '8884:8884'
    networks:
      - network

  postGraphile:
    container_name: udiaas-postgraphile
    image: 'ghcr.io/udi-service/udiaas-postgraphile:latest'
    restart: always
    networks:
      - network
    ports:
      - 5123:5000
    command:
      - '--cors'
      - '--connection'
      - >-
        postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@udiaas-postgres:5432/${POSTGRES_DATABASE}
      - '--host'
      - 0.0.0.0
      - '--cors'
      - '--schema'
      - public
      - '--retry-on-init-fail'
      - '--graphiql'
      - /
      - '--enhance-graphiql'
      - '--simple-collections'
      - both
      - '--append-plugins'
      - >-
        @graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related
      - '--skip-plugins'
      - graphile-build-pg:PgNodeAliasPostGraphile

networks:
  network:
    external:
      name: udiaas