version: '3.3'
services:

  keycloak:
    container_name: keycloak
    image: 'ghcr.io/udi-service/udiaas-keycloak:22.0.4'
    command: start --optimized
    restart: always
    environment:
      - KEYCLOAK_ADMIN=${UDIAAS_KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${UDIAAS_KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB_DATABASE=${UDIAAS_KEYCLOAK_DATABASE}
      - KC_DB_URL=jdbc:postgresql://udiaas-postgres/${UDIAAS_KEYCLOAK_DATABASE}
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=${UDIAAS_POSTGRES_USER}
      - KC_DB_PASSWORD=${UDIAAS_POSTGRES_PASSWORD}
      - KC_HOSTNAME=${UDIAAS_KEYCLOAK_FQDN}
    networks:
      - network
    ports:
      - '${UDIAAS_KEYCLOAK_PORT:-8080}:8080'

  postgres:
    container_name: udiaas-postgres
    image: 'ghcr.io/udi-service/udiaas:15.4'
    restart: always
    environment:
      - POSTGRES_USER=${UDIAAS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${UDIAAS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${UDIAAS_POSTGRES_DATABASE}
    networks:
      - network
    volumes:
      - udiaas-data:/var/lib/postgresql
    ports:
      - '${UDIAAS_POSTGRES_PORT:-5432}:5432'

  postgREST:
    container_name: udiaas-postgrest
    image: postgrest/postgrest:v11.2.1
    restart: always
    environment:
      - PGRST_DB_URI=postgres://${UDIAAS_POSTGRES_USER}:${UDIAAS_POSTGRES_PASSWORD}@udiaas-postgres:5432/${UDIAAS_POSTGRES_DATABASE}
    ports:
      - '${UDIAAS_POSTGREST_PORT:-3000}:3000'
    networks:
      - network

  postGraphile:
    container_name: udiaas-postgraphile
    image: 'ghcr.io/udi-service/udiaas-postgraphile:4.14.0'
    restart: always
    networks:
      - network
    ports:
      - '${UDIAAS_POSTGRAPHILE_PORT:-5000}:5000'
    command:
      - '--cors'
      - '--connection'
      - >-
        postgres://${UDIAAS_POSTGRES_USER}:${UDIAAS_POSTGRES_PASSWORD}@udiaas-postgres:5432/${UDIAAS_POSTGRES_DATABASE}
      - '--host'
      - 0.0.0.0
      - '--cors'
      - '--schema'
      - public
      - '--retry-on-init-fail'
      - '--graphiql'
      - /
      - '--enhance-graphiql'
      - '--simple-collections'
      - both
      - '--append-plugins'
      - >-
        @graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related
      - '--skip-plugins'
      - graphile-build-pg:PgNodeAliasPostGraphile

networks:
  network:
    external:
      name: udiaas
  
volumes:
  udiaas-data:
    name: udiaas-postgres_data
